### REST Client


### Home page
GET http://localhost:3000

### Recuperar todas las películas
GET http://localhost:3000/movies

### Recuperar película por ID
GET http://localhost:3000/movies/24ab6af3-8cf6-4da0-9f32-569c11b63770

### Recuperar todas las películas de un género
GET http://localhost:3000/movies?genre=Crime

### Crear una película con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Batman",
  "year": 2023,
  "director": "Esteban Padilla",
  "duration": 200,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una película
PATCH http://localhost:3000/movies/24ab6af3-8cf6-4da0-9f32-569c11b63770
Content-Type: application/json

{
  "year": 2023
}
